language: node_js
node_js: '10'
script: make build
deploy:
  provider: npm
  email: performance.team@ridi.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: ridi/cms-ui
    branch: master
  skip_cleanup: true
  script: make publish
